-- =========================================================
-- PROJECTS, DIAGRAMS, AND CHATS SCHEMA
-- These tables support the projects feature from temp branch
-- =========================================================

-- ---------------------------------------------------------
-- PROJECTS (PUBLIC_ID AS PRIMARY KEY)
-- PUBLIC_ID = WHAT YOU USE IN ROUTES (E.G., ARCHFIND-XXXX)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
  public_id TEXT PRIMARY KEY,
  user_firebase_uid TEXT NOT NULL REFERENCES users(firebase_uid) ON DELETE CASCADE,

  name TEXT NOT NULL,
  is_temporary BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at TIMESTAMPTZ,

  -- POINTS TO diagram_versions.id (TEXT) - CAN BE NULL
  current_diagram_version_id TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_projects_user
ON projects(user_firebase_uid)
WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_projects_updated_at ON projects;
CREATE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ---------------------------------------------------------
-- DIAGRAM VERSIONS (APP-GENERATED TEXT ID)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS diagram_versions (
  id TEXT PRIMARY KEY, -- GENERATED BY APP (UUID/ULID/STRING)

  project_public_id TEXT NOT NULL REFERENCES projects(public_id) ON DELETE CASCADE,
  user_firebase_uid TEXT NOT NULL REFERENCES users(firebase_uid) ON DELETE CASCADE,

  version_number INT NOT NULL,
  source TEXT NOT NULL,            -- 'canvas_json' | 'chat_upload' | 'image_ocr'
  diagram_json JSONB,              -- RAW DIAGRAM JSON
  image_object_key TEXT,           -- STORAGE KEY (S3/MINIO/LOCAL)
  spec_summary JSONB,              -- NORMALIZED SUMMARY FOR LLM
  hash TEXT,                       -- OPTIONAL DEDUPE HASH
  created_by TEXT REFERENCES users(firebase_uid),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (project_public_id, version_number)
);

CREATE INDEX IF NOT EXISTS idx_diagram_versions_project
ON diagram_versions(project_public_id, version_number DESC);

CREATE INDEX IF NOT EXISTS idx_diagram_versions_user
ON diagram_versions(user_firebase_uid);

CREATE INDEX IF NOT EXISTS idx_diagram_versions_hash
ON diagram_versions(hash);

-- NOW THAT diagram_versions EXISTS, ADD FK FOR current_diagram_version_id
ALTER TABLE projects
DROP CONSTRAINT IF EXISTS projects_current_diagram_version_fk;

ALTER TABLE projects
ADD CONSTRAINT projects_current_diagram_version_fk
FOREIGN KEY (current_diagram_version_id)
REFERENCES diagram_versions(id)
ON DELETE SET NULL;

-- ---------------------------------------------------------
-- CHAT THREADS (APP-GENERATED TEXT ID)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_threads (
  id TEXT PRIMARY KEY, -- GENERATED BY APP

  project_public_id TEXT NOT NULL REFERENCES projects(public_id) ON DELETE CASCADE,
  user_firebase_uid TEXT NOT NULL REFERENCES users(firebase_uid) ON DELETE CASCADE,

  title TEXT,
  binding_mode TEXT NOT NULL DEFAULT 'FOLLOW_LATEST', -- 'FOLLOW_LATEST' | 'PINNED'
  pinned_diagram_version_id TEXT REFERENCES diagram_versions(id),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_threads_project
ON chat_threads(project_public_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_chat_threads_user
ON chat_threads(user_firebase_uid, created_at DESC);

-- ---------------------------------------------------------
-- CHAT MESSAGES (APP-GENERATED TEXT ID)
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_messages (
  id TEXT PRIMARY KEY, -- GENERATED BY APP

  thread_id TEXT NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
  project_public_id TEXT NOT NULL REFERENCES projects(public_id) ON DELETE CASCADE,
  user_firebase_uid TEXT NOT NULL REFERENCES users(firebase_uid) ON DELETE CASCADE,

  role TEXT NOT NULL,      -- 'user' | 'assistant'
  content TEXT NOT NULL,
  source TEXT,             -- 'rag' | 'llm' | 'guardrails'
  refs JSONB,              -- CITATIONS/SNIPPETS/ETC

  diagram_version_id_used TEXT REFERENCES diagram_versions(id),

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_thread
ON chat_messages(thread_id, created_at);

CREATE INDEX IF NOT EXISTS idx_chat_messages_project
ON chat_messages(project_public_id, created_at);

CREATE INDEX IF NOT EXISTS idx_chat_messages_user
ON chat_messages(user_firebase_uid, created_at);

-- ---------------------------------------------------------
-- CHAT MESSAGE ATTACHMENTS
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_message_attachments (
  id TEXT PRIMARY KEY,
  message_id TEXT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,

  kind TEXT NOT NULL DEFAULT 'image',
  object_key TEXT NOT NULL,

  mime_type TEXT,
  file_name TEXT,
  file_size_bytes BIGINT,
  width INT,
  height INT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_message_attachments_message
ON chat_message_attachments(message_id);
